name: Entur/Docker/Build

on:
  workflow_call:
    inputs:
      context:
        description: "Build context, default root of repository"
        type: string
        default: "."
      dockerfile:
        description: "Dockerfile to use for build"
        type: string
        default: "Dockerfile"
      dockerfile_artifact_name:
        description: "Name of Dockerfile GitHub artifact to add to build."
        type: string
      dockerfile_artifact_filename:
        description: "Name of Dockerfile in artifact"
        type: string
        default: "Dockerfile"
      image_name:
        description: "Image name to use for the build"
        type: string
        default: "repo_name"
      build_artifact_name:
        description: "Name of GitHub artifact to add to build"
        type: string
      build_artifact_path:
        description: "Path to the artifact"
        type: string
        default: "build/libs"
      cloud_provider:
        description: "Which cloud service provider to use - Google Cloud: 'gcp' or Azure: 'az'"
        type: string
        default: "gcp"
      timeout_minutes:
        description: "Timeout in minutes"
        type: number
        default: 40
    outputs:
      image_artifact:
        value: ${{ jobs.build.outputs.image_artifact }}
      image_tag:
        value: ${{ jobs.build.outputs.image_tag }}

jobs:
  build:
    name: Docker Build
    runs-on: ubuntu-24.04
    timeout-minutes: ${{ inputs.timeout_minutes }}
    permissions:
      contents: read
      id-token: write
    outputs:
      image_artifact: ${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}
      image_tag: ${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}:latest
    env:
      GHA_DOCKER_BUILD_CONTEXT: ${{ inputs.context }}
      GHA_DOCKER_BUILD_DOCKERFILE: ${{ inputs.dockerfile }}
      GHA_DOCKER_BUILD_DOCKERFILE_ARTIFACT_NAME: ${{ inputs.dockerfile_artifact_name }}
      GHA_DOCKER_BUILD_DOCKERFILE_ARTIFACT_FILENAME: ${{ inputs.dockerfile_artifact_filename }}
      GHA_DOCKER_BUILD_ARTIFACT_PATH: ${{ inputs.build_artifact_path }}
      GHA_DOCKER_BUILD_ARTIFACT_NAME: ${{ inputs.build_artifact_name }}
      GHA_DOCKER_BUILD_IMAGE_NAME: ${{ inputs.image_name }}
      GHA_DOCKER_PUSH_CLOUD_PROVIDER: ${{ inputs.cloud_provider }}
      GHA_REF: ""
    steps:
      - name: Set variables
        id: set-vars
        shell: bash
        run: |
          if [[ "${GHA_DOCKER_BUILD_IMAGE_NAME}" = "repo_name" ]]; then
            echo "GHA_DOCKER_BUILD_IMAGE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          fi
          if [[ "${GITHUB_EVENT_NAME}" = "pull_request" ]]; then
             GHA_REF=${GITHUB_HEAD_REF}
          else
             GHA_REF=${GITHUB_REF_NAME}
          fi
          echo "GHA_REF=${GHA_REF}" >> $GITHUB_ENV

      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GHA_REF }}
          fetch-depth: 0

      - if: env.GHA_DOCKER_BUILD_ARTIFACT_NAME != ''
        name: Download artifact ${{ env.GHA_DOCKER_BUILD_ARTIFACT_NAME }}
        id: download-build-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GHA_DOCKER_BUILD_ARTIFACT_NAME }}
          path: ${{ env.GHA_DOCKER_BUILD_ARTIFACT_PATH }}

      - if: env.GHA_DOCKER_BUILD_ARTIFACT_NAME != ''
        name: List artifacts in ${{ env.GHA_DOCKER_BUILD_ARTIFACT_PATH }}
        id: list-build-artifacts
        shell: bash
        run: ls -l ${{ env.GHA_DOCKER_BUILD_ARTIFACT_PATH }}

      - if: env.GHA_DOCKER_BUILD_DOCKERFILE_ARTIFACT_NAME != ''
        name: Download Dockerfile artifact
        id: download-dockerfile-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GHA_DOCKER_BUILD_DOCKERFILE_ARTIFACT_NAME }}
          path: /tmp/dockerfile-artifact/

      - if: env.GHA_DOCKER_BUILD_DOCKERFILE_ARTIFACT_NAME != ''
        name: Set Dockerfile path in env for build step
        id: set-dockerfile-path
        run: |
          # If Dockerfile already exists in repo, use that for building. If Dockerfile artifact is given and a
          # Dockerfile does not exist in repo, build directly from artifact instead.
          if [ ! -f "${{ GHA_DOCKER_BUILD_DOCKERFILE }}" ]; then
            echo "GHA_DOCKER_BUILD_DOCKERFILE=/tmp/dockerfile-artifact/${{ GHA_DOCKER_BUILD_DOCKERFILE_ARTIFACT_FILENAME }}" >> $GITHUB_ENV
          fi
            
      - name: Setup buildx
        id: setup-buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Authenticate with the cloud provider
        id: auth
        uses: entur/gha-meta/.github/actions/docker-auth@v1
        with:
          cloud_provider: ${{ env.GHA_DOCKER_PUSH_CLOUD_PROVIDER }}
          gcp_workload_identity_provider: ${{ vars.CI_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ vars.CI_SERVICE_ACCOUNT }}
          azure_client_id: ${{ vars.CI_AZURE_CLIENT_ID }}
          azure_tenant_id: ${{ vars.CI_AZURE_TENANT_ID }}
          azure_subscription_id: ${{ vars.CI_AZURE_SUBSCRIPTION_ID }}

      - name: Build image
        id: build
        uses: docker/build-push-action@v6.7.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ env.GHA_DOCKER_BUILD_CONTEXT }}
          file: ${{ env.GHA_DOCKER_BUILD_DOCKERFILE }}
          outputs: "type=docker,dest=/tmp/${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}.tar"
          push: false
          provenance: false
          tags: ${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}:${{ github.sha }}

      - name: Save docker image to the artifact storage
        id: save-image
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}
          path: /tmp/${{ env.GHA_DOCKER_BUILD_IMAGE_NAME }}.tar
          retention-days: 4 # TODO discuss this or make it a parameter
