name: release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  # needed for status checks pr approvals
  update-lint-doc:
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/lint.yml
      readme_file: README-lint.md
  update-build-doc:
    needs: [update-lint-doc]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/build.yml
      readme_file: README-build.md
  update-push-doc:
    needs: [update-build-doc]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/push.yml
      readme_file: README-push.md
  # / needed for status checks pr approvals
  release:
    needs: [update-push-doc]
    uses: entur/gha-meta/.github/workflows/release.yml@v1
