name: Entur/Docker/CI

on:
  pull_request:

jobs:
  update-lint-doc:
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/lint.yml
      readme_file: README-lint.md

  update-build-doc:
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/build.yml
      readme_file: README-build.md

  update-push-doc:
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/push.yml
      readme_file: README-push.md

  test-lint-ok:
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.good
      timeout_minutes: 1

  test-lint-ignore-ok:
    uses: ./.github/workflows/lint.yml
    with:
      dockerfile: fixture/Dockerfile.bad
      ignore: DL3000

  test-lint-fail-ok:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: hadolint/hadolint-action@v3.1.0
        id: hadolint
        continue-on-error: true
        with:
          no-fail: true
          dockerfile: fixture/Dockerfile.bad
      - uses: nick-fields/assert-action@v2
        with:
          expected: "fixture/Dockerfile.bad:4 DL3000 error: Use absolute WORKDIR"
          actual: ${{ env.HADOLINT_RESULTS }}

  test-build-prepare-artifact:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/upload-artifact@v4.3.3
        with:
          name: some_build_artifact
          path: fixture/artifact.txt
          retention-days: 1
          overwrite: true

  test-build-ok-with-artifact:
    uses: ./.github/workflows/build.yml
    needs: test-build-prepare-artifact
    with:
      context: .
      dockerfile: fixture/Dockerfile.artifact
      build_artifact_name: some_build_artifact
      build_artifact_path: data

  test-build-ok-with-artifact-outputs:
    runs-on: ubuntu-24.04
    needs: test-build-ok-with-artifact
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "gha-docker:latest"
          actual: ${{ needs.test-build-ok-with-artifact.outputs.image_tag }}
      - uses: nick-fields/assert-action@v2
        with:
          expected: "gha-docker"
          actual: ${{ needs.test-build-ok-with-artifact.outputs.image_artifact }}

  test-build-ok-with-custom-image-name:
    uses: ./.github/workflows/build.yml
    with:
      dockerfile: "fixture/Dockerfile.good"
      image_name: "custom_image_name"

  test-build-ok-with-custom-image-name-outputs:
    runs-on: ubuntu-24.04
    needs: test-build-ok-with-custom-image-name
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "custom_image_name:latest"
          actual: ${{ needs.test-build-ok-with-custom-image-name.outputs.image_tag }}
      - uses: nick-fields/assert-action@v2
        with:
          expected: "custom_image_name"
          actual: ${{ needs.test-build-ok-with-custom-image-name.outputs.image_artifact }}

  test-push-gcr-ok:
    needs: test-build-ok-with-artifact
    uses: ./.github/workflows/push.yml
    with:
      environment: dev
      context: .
      dockerfile: fixture/Dockerfile.artifact

  test-push-gcr-ok-with-tag:
    needs: test-build-ok-with-artifact
    uses: ./.github/workflows/push.yml
    with:
      environment: dev
      context: .
      dockerfile: fixture/Dockerfile.artifact
      image_tag: "ci-test-tag"

  test-tag-gcr-outputs-ok:
    runs-on: ubuntu-24.04
    needs: test-push-gcr-ok-with-tag
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "ci-test-tag"
          actual: ${{ needs.test-push-gcr-ok-with-tag.outputs.image_tag }}

  test-push-acr-ok-with-tag:
    needs: test-build-ok-with-artifact
    uses: ./.github/workflows/push.yml
    with:
      environment: az-dev
      cloud_provider: az
      context: .
      dockerfile: fixture/Dockerfile.artifact
      image_tag: "ci-test-tag"

  test-tag-acr-outputs-ok:
    runs-on: ubuntu-24.04
    needs: test-push-acr-ok-with-tag
    steps:
      - uses: nick-fields/assert-action@v2
        with:
          expected: "ci-test-tag"
          actual: ${{ needs.test-push-acr-ok-with-tag.outputs.image_tag }}
