name: Entur/Docker/Push

on:
  workflow_call:
    inputs:
      image_artifact_name:
        description: "GitHub artifact with Docker image"
        type: string
        default: "repo_name"
      environment:
        type: string
        description: "GitHub environment to use"
        default: "prd"
      dockerfile_name:
        description: "Dockerfile to use for build"
        type: string
        default: "Dockerfile"
      docker_tag:
        description: "Docker tag"
        type: string
        default: "docker_tag"
      repository_type:
        description: "Which repository to use. GCR/ACR"
        type: string
        default: "GCR"
    outputs:
      image_name:
        value: ${{ jobs.push.outputs.image_name }}
      docker_tag:
        value: ${{ jobs.push.outputs.docker_tag }}

jobs:
  push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    outputs:
      image_name: ${{ steps.push.outputs.metadata }}
      docker_tag: ${{ env.GHA_DOCKER_PUSH_DOCKER_TAG }}

    timeout-minutes: 10
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_DOCKER_PUSH_IMAGE_ARTIFACT_NAME=${{ inputs.image_artifact_name }}" >> $GITHUB_ENV
          echo "GHA_DOCKER_PUSH_GCR_PROJECT_ID=entur-system-1287" >> $GITHUB_ENV
          echo "GHA_DOCKER_PUSH_DOCKERFILE_NAME=${{ inputs.dockerfile_name }}" >> $GITHUB_ENV
          echo "GHA_DOCKER_PUSH_DOCKER_TAG=${{ inputs.docker_tag }}" >> $GITHUB_ENV
      - id: set-image-name
        shell: bash
        run: |
          if [[ "${{ env.GHA_DOCKER_PUSH_IMAGE_ARTIFACT_NAME }}" = "repo_name" ]]; then
            echo "GHA_DOCKER_PUSH_IMAGE_ARTIFACT_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          fi
      - id: set-shorten-branch-name-env
        shell: bash
        # This shortens a branch name (max 63 chars) and removes illegal characters for tags/labels in Helm / GCP.
        # It will:
        # Shorten to max length
        # Removes any "-" if last
        # Convert to lowercase and removes Norwegian characters
        # Removes "/" slashes, e.g. feature/ETU... to feature-ETU... because illegal in labels in Helm / GCP
        # Removes dots, e.g. feature.ETU... to feature-ETU... because it fails matching in Deploy system
        # Removes exclamation marks, e.g. feature!ETU... to feature-ETU... because it fails matching in Deploy system
        run: |
          if [[ "${{ github.event_name }}" = "pull_request" ]]; then
            BRANCH_NAME=${{ github.head_ref }}
          else
            BRANCH_NAME=${{ github.ref_name }}
          fi
          SHORT_BRANCH_NAME=${BRANCH_NAME:0:55}
          SHORT_BRANCH_NAME=$(echo "$SHORT_BRANCH_NAME" | sed s'/[-]$//')
          SHORT_BRANCH_NAME=$(echo "$SHORT_BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr -d '[ÆØÅæøå]')
          SHORT_BRANCH_NAME=${SHORT_BRANCH_NAME//\//-}
          SHORT_BRANCH_NAME=${SHORT_BRANCH_NAME//./-}
          SHORT_BRANCH_NAME=${SHORT_BRANCH_NAME//!/-}
          echo "GHA_DOCKER_PUSH_BRANCH_TAG=$SHORT_BRANCH_NAME" >> $GITHUB_ENV
      - id: set-date-env
        shell: bash
        run: echo "GHA_DOCKER_PUSH_DATE=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
      - id: set-docker-tag-from-input-env
        shell: bash
        run: |
          if [[ "${{ env.GHA_DOCKER_PUSH_DOCKER_TAG }}" = "docker_tag" ]]; then
            SHA=${{ github.sha }}
            SHORT_SHA=${SHA:0:7}
            echo "GHA_DOCKER_PUSH_DOCKER_TAG=${{ env.GHA_DOCKER_PUSH_BRANCH_TAG }}.${{ env.GHA_DOCKER_PUSH_DATE }}-SHA$SHORT_SHA" >> $GITHUB_ENV
          fi
      - id: set-repository-env
        shell: bash
        run: |
          if [[ "${{ inputs.repository_type }}" = "GCR" ]]; then
            echo "GHA_DOCKER_PUSH_META_IMAGES=eu.gcr.io/${{ env.GHA_DOCKER_PUSH_GCR_PROJECT_ID }}/${{ env.GHA_DOCKER_PUSH_IMAGE_ARTIFACT_NAME }}" >> $GITHUB_ENV
          elif [[ "${{ inputs.repository_type }}" = "ACR" ]]; then
            echo "GHA_DOCKER_PUSH_META_IMAGES=acrentur001.azurecr.io/${{ env.GHA_DOCKER_PUSH_IMAGE_ARTIFACT_NAME }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4.1.2
      - uses: docker/setup-buildx-action@v3.2.0
      - id: auth
        uses: google-github-actions/auth@v2.1.2
        if: ${{ inputs.repository_type == 'GCR' }}
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          token_format: 'access_token'
      - id: login-gcr
        uses: docker/login-action@v3.1.0
        if: ${{ inputs.repository_type == 'GCR' }}
        with:
          registry: eu.gcr.io
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - id: login-azure
        uses: Azure/login@v2
        if: ${{ inputs.repository_type == 'ACR' }}
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - id: login-acr
        if: ${{ inputs.repository_type == 'ACR' }}
        shell: bash
        run: |
          az acr login --name acrentur001
      - id: download-image-artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.GHA_DOCKER_PUSH_IMAGE_ARTIFACT_NAME }}
          path: /tmp
      - id: load-image
        run: |
          docker load --input /tmp/${{ env.GHA_DOCKER_PUSH_IMAGE_ARTIFACT_NAME }}.tar
      - id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.GHA_DOCKER_PUSH_META_IMAGES }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=${{ env.GHA_DOCKER_PUSH_BRANCH_TAG }}
            type=raw,value=${{ env.GHA_DOCKER_PUSH_DOCKER_TAG }}
      - id: push
        uses: docker/build-push-action@v5.3.0
        with:
          file: ${{ env.GHA_DOCKER_PUSH_DOCKERFILE_NAME }}
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
