name: Entur/Docker/Push

on:
  workflow_call:
    inputs:
      image_name:
        description: "GitHub artifact with Docker image"
        type: string
        default: "repo_name"
      environment:
        type: string
        description: "GitHub environment to use"
        default: "prd"
      dockerfile:
        description: "Dockerfile to use for build"
        type: string
        default: "Dockerfile"
      image_tag:
        description: "Docker tag"
        type: string
        default: "image_tag"
      cloud_provider:
        description: "Which repository to use. GCP/Azure"
        type: string
        default: "GCP"
    outputs:
      meta:
        value: ${{ jobs.push.outputs.meta }}
      image_name:
        value: ${{ jobs.push.outputs.image_name }}
      image_tag:
        value: ${{ jobs.push.outputs.image_tag }}

jobs:
  push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    outputs:
      meta: ${{ steps.push.outputs.metadata }}
      image_name: ${{ env.GHA_DOCKER_PUSH_IMAGE_NAME }}
      image_tag: ${{ env.GHA_DOCKER_PUSH_IMAGE_TAG }}

    timeout-minutes: 10
    steps:
      - id: set-env
        shell: bash
        run: |
          echo "GHA_DOCKER_PUSH_IMAGE_NAME=${{ inputs.image_name }}" >> $GITHUB_ENV
          echo "GHA_DOCKER_PUSH_DOCKERFILE=${{ inputs.dockerfile }}" >> $GITHUB_ENV
          echo "GHA_DOCKER_PUSH_IMAGE_TAG=${{ inputs.image_tag }}" >> $GITHUB_ENV
          echo "GHA_DOCKER_PUSH_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "GHA_DOCKER_PUSH_CLOUD_PROVIDER=${{ inputs.cloud_provider }}" >> $GITHUB_ENV
          # Convert ref name to a valid git & docker tag name
          if [[ "${{ github.event_name }}" = "pull_request" ]]; then
            BRANCH_NAME=${{ github.head_ref }}
          else
            BRANCH_NAME=${{ github.ref_name }}
          fi
          BRANCH_NAME=${BRANCH_NAME:0:43} # truncate to max_len - len(.YYYYMMDD-SHA1234567)
          BRANCH_NAME=$(echo "$BRANCH_NAME" | sed s'/[-]$//') # remove trailing -
          BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | tr -d '[ÆØÅæøå]') # to ASCII lower case
          BRANCH_NAME=${BRANCH_NAME//\//-} # replace / with -
          BRANCH_NAME=${BRANCH_NAME//./-}  # replace . with -
          BRANCH_NAME=${BRANCH_NAME//!/-}  # replace ! with -
          echo "GHA_DOCKER_PUSH_BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      - id: verify-cloud-provider
        shell: bash
        if: env.GHA_DOCKER_PUSH_CLOUD_PROVIDER != 'GCP' && env.GHA_DOCKER_PUSH_CLOUD_PROVIDER != 'Azure'
        run: |
          echo "cloud_provider can only be GCP or Azure"
          exit 1
      - id: set-image-artifact-name
        shell: bash
        if: env.GHA_DOCKER_PUSH_IMAGE_NAME == 'repo_name'
        run: |
          echo "GHA_DOCKER_PUSH_IMAGE_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - id: set-image-tag
        shell: bash
        if: env.GHA_DOCKER_PUSH_IMAGE_TAG  == 'image_tag'
        run: |
          SHA=${{ github.sha }}
          SHORT_SHA=${SHA:0:7}
          echo "GHA_DOCKER_PUSH_IMAGE_TAG=${{ env.GHA_DOCKER_PUSH_BRANCH_NAME }}.${{ env.GHA_DOCKER_PUSH_DATE }}-SHA${SHORT_SHA}" >> $GITHUB_ENV
      - id: set-registry-azure
        shell: bash
        if: env.GHA_DOCKER_PUSH_CLOUD_PROVIDER  == 'Azure'
        run: |
          echo "GHA_DOCKER_PUSH_DOCKER_REGISTRY=acrentur001.azurecr.io" >> $GITHUB_ENV
      - id: set-registry-gcp
        shell: bash
        if: env.GHA_DOCKER_PUSH_CLOUD_PROVIDER  == 'GCP'
        run: |
          echo "GHA_DOCKER_PUSH_DOCKER_REGISTRY=eu.gcr.io/entur-system-1287" >> $GITHUB_ENV
      - id: set-image
        shell: bash
        run: |
          echo "GHA_DOCKER_PUSH_IMAGE=${{ env.GHA_DOCKER_PUSH_DOCKER_REGISTRY}}/${{ env.GHA_DOCKER_PUSH_IMAGE_NAME }}" >> $GITHUB_ENV
      - uses: actions/checkout@v4.1.4
      - uses: docker/setup-buildx-action@v3.3.0
      - id: login-gcp
        uses: google-github-actions/auth@v2.1.2
        if: inputs.cloud_provider == 'GCP'
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          token_format: "access_token"
      - id: login-gcr
        uses: docker/login-action@v3.1.0
        if: inputs.cloud_provider == 'GCP'
        with:
          registry: eu.gcr.io
          username: oauth2accesstoken
          password: ${{ steps.login-gcp.outputs.access_token }}
      - id: login-azure
        uses: Azure/login@v2
        if: inputs.cloud_provider == 'Azure'
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      - id: login-acr
        if: inputs.cloud_provider == 'Azure'
        shell: bash
        run: |
          az acr login --name acrentur001
      - id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.GHA_DOCKER_PUSH_IMAGE }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=${{ env.GHA_DOCKER_PUSH_BRANCH_NAME }}
            type=raw,value=${{ env.GHA_DOCKER_PUSH_IMAGE_TAG }}
      - id: push
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          cache-from: type=gha
          file: ${{ env.GHA_DOCKER_PUSH_DOCKERFILE }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
